# 2024-12-27

### 조건부 표현식

In [3]:
score = 80

if score >= 60:
    message="success"

else:
    message = "failure"

print(message)

success


In [6]:
message = "success" if score >= 60 else "failure"

print(message)

success


### list comperhension(리스트 컴프리헨션)

In [8]:
squares = []
numbers = [1, 2, 3, 4, 5]
for x in numbers:
    squares.append(x**2)

print(squares)

[1, 4, 9, 16, 25]


In [12]:
squares2 = [x**2 for x in numbers]

print(squares2)

[1, 4, 9, 16, 25]


In [22]:
# 조건부 표현식과 리스트 컴프리헨션의 조합

# num 중 짝수인 것만

num = [1, 2, 3, 4, 5, 6, 7]
even_numbers = [a for a in num if a%2 == 0]
print(even_numbers)

[2, 4, 6]


## NumPy

연산을 위한 라이브러리

In [27]:
!pip install numpy

In [25]:
import numpy as np

In [26]:
np.__version__

'2.2.1'

In [28]:
# 파이썬의 리스트 생성

a_list = [1, 2, 3, 4]
a_list

[1, 2, 3, 4]

In [29]:
type(a_list)

list

In [31]:
int_arr = np.array([1, 2, 3, 4])
int_arr

array([1, 2, 3, 4])

In [32]:
print(int_arr)

[1 2 3 4]


In [33]:
type(int_arr)

numpy.ndarray

In [35]:
list_data = [1, 2.2, 3]
arr = np.array(list_data)

print(arr)
print(type(arr))

[1.  2.2 3. ]
<class 'numpy.ndarray'>


In [37]:
list_data = [1, 2.2, 3, [3, 4]]
arr = np.array(list_data)

print(arr)
print(type(arr))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [41]:
arr1 = np.arange(1, 10, 2)

arr1

array([1, 3, 5, 7, 9])

#### 특별한 값을 갖는 배열

In [50]:
arr = np.zeros(10, dtype = int)

print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [51]:
arr = np.zeros((2, 5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
arr = np.ones(10, dtype = int)

print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [58]:
arr = np.eye(5, dtype = int)

print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


#### n차원 배열 ndim, shape, reshape

In [68]:
#2차원 배열

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], 
                [9, 10, 11, 12], [13, 14, 15, 16]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [63]:
#3차원 배열

arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], 
                [[9, 10, 11, 12], [13, 14, 15, 16]]])

print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [69]:
int_arr = np.array([1, 2, 3, 4])
print(int_arr)
print(int_arr.ndim)
print(int_arr.shape)

[1 2 3 4]
1
(4,)


In [71]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], 
                [9, 10, 11, 12], [13, 14, 15, 16]])

print(arr)
print(arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr.reshape(-1, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr.reshape(2, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [80]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr.reshape(2, 6)

ValueError: cannot reshape array of size 10 into shape (2,6)

#### array 연산

In [83]:
a = [1, 2, 3]
b = [4, 5, 6]

print(type(a), type(b))

c = a+b
print(c)
print(a*3)

<class 'list'> <class 'list'>
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [85]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(type(a), type(b))

c = a+b
print(c)
print(a*3)
print(a*b)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[5 7 9]
[3 6 9]
[ 4 10 18]


In [92]:
#원래의 방식으로 list 2배 - 비교를 위하여하여

data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#print(type(data[3]))
for i in data:
    data[i] = data[i]*2

print(data)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [95]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

data2 = []

for i in data:
    data2.append(2*i)
print(data2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [96]:
c = np.array([[1, 2, 3], [4, 5, 6]])

print(c)
print(len(c))
print(len(c[0]))

[[1 2 3]
 [4 5 6]]
2
3


### array indexing

In [97]:
# array indexing

a = np.array([0, 1, 2, 3, 4])

print(a[2])
print(a[-1])

2
4


In [98]:
a = np.array([[0, 1, 2], [3, 4, 5]])

print(a[0][0], a[0][1], a[1][-1])


0 1 5


In [107]:
#열 출력

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(a[:, 1])

[5 6 7]


In [112]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(a[:2, :2])

[[0 1]
 [4 5]]


In [118]:
# 연산

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2* a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


#### Fancy indexing

In [119]:
#boolean

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [124]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a >5 )
#a[a%2 ==0]

a[ a>5 ]

[False False False False False False  True  True  True  True]


array([6, 7, 8, 9])

In [126]:
#integer

a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 1, 4, 6, 8])
a[idx]

array([11, 22, 55, 77, 99])

In [128]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 1, 1, 6, 2, 2, 2, 5, 5, 5, 5])
a[idx]

array([11, 11, 22, 22, 77, 33, 33, 33, 66, 66, 66, 66])

In [131]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[:, [True, False, False, True]])
print(a[:, [0, 3]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [132]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [134]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a[:, ::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [137]:
# 배열에서 3의 배수를 찾아주세요.
 
# 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
 
# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.

x = np.array([1, 2, 3,4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[x%3 == 0])

print(x[x%4 == 1])

print(x[(x%3 == 0) & (x%4 ==1)])
 

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


## Pandas

In [139]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ------ --------------------------------- 1.8/11.5 MB 9.5 MB/s eta 0:00:02
   ------------- -------------------------- 3.9/11.5 MB 9.5 MB/s eta 0:00:01
   --------------------- ------------------ 6.0/11.5 MB 9.6 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.5 MB 9.6 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 8.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [141]:
import pandas as pd

In [142]:
pd.__version__

'2.2.3'

#### Series

In [145]:
s = pd.Series([-3, 5, 7, 4])
print(s)
print(type(s))

0   -3
1    5
2    7
3    4
dtype: int64
<class 'pandas.core.series.Series'>


In [147]:
s = pd.Series([-3, 5, 7, 4], index = ['a', 'b', 'c', 'd'])
print(s)
print(type(s))

a   -3
b    5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [148]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [150]:
s.values

array([-3,  5,  7,  4])

In [151]:
print(s[0])

-3


C:\Users\USER\AppData\Local\Temp\ipykernel_12388\287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [153]:
print(s['a'])

-3


#### DataFrame

In [156]:
df = pd.DataFrame([['부산광역시', '051', 3364358], 
                   ['전라남도', '061', 1840921],
                   ['강원도', '033', 1553355]])

df

0    1        2
0  부산광역시  051  3364358
1   전라남도  061  1840921
2    강원도  033  1553355

In [157]:
df = pd.DataFrame({'Division': ['부산광역시', '전라남도', '강원도'],
                   'Code': ['051', '061', '033'],
                   'Population': [3364358, 1840921, 1553355]})

df

Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1553355

In [158]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [160]:
df.columns

Index(['Division', 'Code', 'Population'], dtype='object')

In [162]:
df.values

array([['부산광역시', '051', 3364358],
       ['전라남도', '061', 1840921],
       ['강원도', '033', 1553355]], dtype=object)

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [164]:
df.set_index('Division')

Code  Population
Division                 
부산광역시     051     3364358
전라남도      061     1840921
강원도       033     1553355

In [166]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [172]:
pd.options.display.float_format = '{:,.0f}'.format

df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11,500,000,000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270  1,000,000,000
5   캡틴마블  25    파일럿     미국  170    340,000,000
6  블랙위도우  32    스파이    러시아  170     50,000,000

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [175]:
df.head()

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11,500,000,000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270  1,000,000,000

In [176]:
df.tail()

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [179]:
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2,578,000,120
std    13  36  5,003,440,739
min    18 170            600
25%    26 172     50,000,000
50%    32 177    340,000,000
75%    39 184  1,000,000,000
max    58 270 11,500,000,000

In [183]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [186]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [189]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [190]:
df.nlargest(3, '나이')

이름  나이     직업     국적    키             재산
0  아이언맨  58    CEO     미국  174 11,500,000,000
1    토르  45      신  아스가르드  190            NaN
4    헐크  33  핵물리학자     미국  270  1,000,000,000

In [193]:
df.나이

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [195]:
df['나이']

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [198]:
df[['이름', '나이', '직업']]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자
5   캡틴마블  25    파일럿
6  블랙위도우  32    스파이

In [199]:
df[0:2]

이름  나이   직업     국적    키             재산
0  아이언맨  58  CEO     미국  174 11,500,000,000
1    토르  45    신  아스가르드  190            NaN

In [200]:
df.iloc[0]

이름             아이언맨
나이               58
직업              CEO
국적               미국
키               174
재산   11,500,000,000
Name: 0, dtype: object

In [207]:
df.iloc[0:5, 0:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [211]:
df2 = df.copy()
df2.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

df2

이름  나이     직업     국적    키             재산
a   아이언맨  58    CEO     미국  174 11,500,000,000
b     토르  45      신  아스가르드  190            NaN
c  스파이더맨  18   고등학생     미국  177            600
d   원더우먼  27     공주  데미스키라  178            NaN
e     헐크  33  핵물리학자     미국  270  1,000,000,000
f   캡틴마블  25    파일럿     미국  170    340,000,000
g  블랙위도우  32    스파이    러시아  170     50,000,000

In [213]:
df2.loc['a' : 'b']

이름  나이   직업     국적    키             재산
a  아이언맨  58  CEO     미국  174 11,500,000,000
b    토르  45    신  아스가르드  190            NaN

In [217]:
df2.loc['a': 'b', ['이름', '직업']]

이름   직업
a  아이언맨  CEO
b    토르    신

In [224]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [221]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [225]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [223]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [244]:
df.loc[:, '나이']

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [ ]:
df[df['나이'] > 30]

In [245]:
df[(df['나이'] >30) & (df['나이']<50)]

이름  나이     직업     국적    키            재산
1     토르  45      신  아스가르드  190           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [248]:
df_a = df.sort_values('키', ascending= False)
df_a

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270  1,000,000,000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11,500,000,000
5   캡틴마블  25    파일럿     미국  170    340,000,000
6  블랙위도우  32    스파이    러시아  170     50,000,000

In [249]:
df2

이름  나이     직업     국적    키             재산
a   아이언맨  58    CEO     미국  174 11,500,000,000
b     토르  45      신  아스가르드  190            NaN
c  스파이더맨  18   고등학생     미국  177            600
d   원더우먼  27     공주  데미스키라  178            NaN
e     헐크  33  핵물리학자     미국  270  1,000,000,000
f   캡틴마블  25    파일럿     미국  170    340,000,000
g  블랙위도우  32    스파이    러시아  170     50,000,000

In [251]:
df2['국적'] = '대한민국'
df2

이름  나이     직업    국적    키             재산
a   아이언맨  58    CEO  대한민국  174 11,500,000,000
b     토르  45      신  대한민국  190            NaN
c  스파이더맨  18   고등학생  대한민국  177            600
d   원더우먼  27     공주  대한민국  178            NaN
e     헐크  33  핵물리학자  대한민국  270  1,000,000,000
f   캡틴마블  25    파일럿  대한민국  170    340,000,000
g  블랙위도우  32    스파이  대한민국  170     50,000,000

In [253]:
df2['전투력'] = [90, 100, 46, 79, 89, 78, 65]
df2

이름  나이     직업    국적    키             재산  전투력
a   아이언맨  58    CEO  대한민국  174 11,500,000,000   90
b     토르  45      신  대한민국  190            NaN  100
c  스파이더맨  18   고등학생  대한민국  177            600   46
d   원더우먼  27     공주  대한민국  178            NaN   79
e     헐크  33  핵물리학자  대한민국  270  1,000,000,000   89
f   캡틴마블  25    파일럿  대한민국  170    340,000,000   78
g  블랙위도우  32    스파이  대한민국  170     50,000,000   65

In [255]:
df2['전투력'] = df2['전투력'] - 5
df2

이름  나이     직업    국적    키             재산  전투력
a   아이언맨  58    CEO  대한민국  174 11,500,000,000   80
b     토르  45      신  대한민국  190            NaN   90
c  스파이더맨  18   고등학생  대한민국  177            600   36
d   원더우먼  27     공주  대한민국  178            NaN   69
e     헐크  33  핵물리학자  대한민국  270  1,000,000,000   79
f   캡틴마블  25    파일럿  대한민국  170    340,000,000   68
g  블랙위도우  32    스파이  대한민국  170     50,000,000   55

In [260]:
df2.columns = ['성별', '연령', '하는 일', '출신국가', '신장', '재산현황', '파워']
df2

성별  연령   하는 일  출신국가   신장           재산현황  파워
a   아이언맨  58    CEO  대한민국  174 11,500,000,000  80
b     토르  45      신  대한민국  190            NaN  90
c  스파이더맨  18   고등학생  대한민국  177            600  36
d   원더우먼  27     공주  대한민국  178            NaN  69
e     헐크  33  핵물리학자  대한민국  270  1,000,000,000  79
f   캡틴마블  25    파일럿  대한민국  170    340,000,000  68
g  블랙위도우  32    스파이  대한민국  170     50,000,000  55

In [261]:
df2.drop(index = ['a'])

성별  연령   하는 일  출신국가   신장          재산현황  파워
b     토르  45      신  대한민국  190           NaN  90
c  스파이더맨  18   고등학생  대한민국  177           600  36
d   원더우먼  27     공주  대한민국  178           NaN  69
e     헐크  33  핵물리학자  대한민국  270 1,000,000,000  79
f   캡틴마블  25    파일럿  대한민국  170   340,000,000  68
g  블랙위도우  32    스파이  대한민국  170    50,000,000  55

In [262]:
df2

성별  연령   하는 일  출신국가   신장           재산현황  파워
a   아이언맨  58    CEO  대한민국  174 11,500,000,000  80
b     토르  45      신  대한민국  190            NaN  90
c  스파이더맨  18   고등학생  대한민국  177            600  36
d   원더우먼  27     공주  대한민국  178            NaN  69
e     헐크  33  핵물리학자  대한민국  270  1,000,000,000  79
f   캡틴마블  25    파일럿  대한민국  170    340,000,000  68
g  블랙위도우  32    스파이  대한민국  170     50,000,000  55

In [267]:
df2.drop(columns=['파워'], inplace= True)

In [268]:
df2

성별  연령   하는 일  출신국가   신장          재산현황
b     토르  45      신  대한민국  190           NaN
c  스파이더맨  18   고등학생  대한민국  177           600
d   원더우먼  27     공주  대한민국  178           NaN
e     헐크  33  핵물리학자  대한민국  270 1,000,000,000
f   캡틴마블  25    파일럿  대한민국  170   340,000,000
g  블랙위도우  32    스파이  대한민국  170    50,000,000

In [269]:
df2.dropna()

성별  연령   하는 일  출신국가   신장          재산현황
c  스파이더맨  18   고등학생  대한민국  177           600
e     헐크  33  핵물리학자  대한민국  270 1,000,000,000
f   캡틴마블  25    파일럿  대한민국  170   340,000,000
g  블랙위도우  32    스파이  대한민국  170    50,000,000

In [270]:
df2

성별  연령   하는 일  출신국가   신장          재산현황
b     토르  45      신  대한민국  190           NaN
c  스파이더맨  18   고등학생  대한민국  177           600
d   원더우먼  27     공주  대한민국  178           NaN
e     헐크  33  핵물리학자  대한민국  270 1,000,000,000
f   캡틴마블  25    파일럿  대한민국  170   340,000,000
g  블랙위도우  32    스파이  대한민국  170    50,000,000

In [271]:
df2.dropna(axis = 1)

성별  연령   하는 일  출신국가   신장
b     토르  45      신  대한민국  190
c  스파이더맨  18   고등학생  대한민국  177
d   원더우먼  27     공주  대한민국  178
e     헐크  33  핵물리학자  대한민국  270
f   캡틴마블  25    파일럿  대한민국  170
g  블랙위도우  32    스파이  대한민국  170

#### null값 채우기

In [273]:
df2.fillna(0)

성별  연령   하는 일  출신국가   신장          재산현황
b     토르  45      신  대한민국  190             0
c  스파이더맨  18   고등학생  대한민국  177           600
d   원더우먼  27     공주  대한민국  178             0
e     헐크  33  핵물리학자  대한민국  270 1,000,000,000
f   캡틴마블  25    파일럿  대한민국  170   340,000,000
g  블랙위도우  32    스파이  대한민국  170    50,000,000

In [280]:
#df2.fillna(method = 'ffill')
df2.fillna(method = 'bfill')

C:\Users\USER\AppData\Local\Temp\ipykernel_12388\3416227212.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method = 'bfill')


성별  연령   하는 일  출신국가   신장          재산현황
b     토르  45      신  대한민국  190           600
c  스파이더맨  18   고등학생  대한민국  177           600
d   원더우먼  27     공주  대한민국  178 1,000,000,000
e     헐크  33  핵물리학자  대한민국  270 1,000,000,000
f   캡틴마블  25    파일럿  대한민국  170   340,000,000
g  블랙위도우  32    스파이  대한민국  170    50,000,000

In [278]:
df2['재산현황'].fillna(df2['재산현황'].mean())

b     347,500,150
c             600
d     347,500,150
e   1,000,000,000
f     340,000,000
g      50,000,000
Name: 재산현황, dtype: float64